config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session_path
  end

  root to: 'pages#home'

  get 'about', to: 'pages#about'

  # my articles routes are all here:
  resources :articles
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable :registerable,
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy
  has_one_attached :photo

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = policy_scope(Article).paginate(page: params[:page], per_page: 5)
    @colors = ['#0476f1', '#cbbada', '#e7e5e6', '#f4c524']
  end

  def show
    @colors = ['#0476f1', '#cbbada', '#e7e5e6', '#f4c524']
    authorize @article
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article
    if @article.save
      flash[:notice] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new', status: :unprocessable_entity
      # So I can use @article in new because I'm rendering
      # it from the create method!
    end
  end

  def edit
    authorize @article
  end

  def update
    authorize @article
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :photo)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home about]
  def home
    @colors = ['#0476f1', '#cbbada', '#e7e5e6', '#f4c524']
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @users = policy_scope(User).all
  end

  def show
    @colors = ['#0476f1', '#cbbada', '#e7e5e6', '#f4c524']
    authorize @user
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      flash[:notice] = "Hey #{@user.username}, your account was successfully updated"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.destroy
    flash[:notice] = 'Account and all articles associated deleted'
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles.html.erb
<div class="articles-container mt-3">
  <% @articles.each do |article| %>
    <div class="article d-flex flex-column justify-content-between" style="background-color: <%= @colors.sample %>">
      <p>Created on <%= article.created_at.strftime('%m/%d/%Y') %></p>
      <img src="" alt="">
      <div class="article-content">
        <h3><%= article.title %></h3>
      </div>
      <%= link_to "Read more", article_path(article), class: "btn-small btn-underline"%>
    </div>
  <% end %>
  </div>

app/views/articles/_form.html.erb
<div class="form create-article mt-3">
  <%= simple_form_for @article do |f| %>
    <%= f.input :title, label: "Title" %>
    <%= f.input :description, label: "Description" %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "btn-sharp" %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="container mt-5">
  <%= link_to "Go back", article_path(@article), class: "btn-small btn-underline" %>
  <h1 class="mt-3">Edit article</h1>
  <%= render 'articles/form' %>
</div>

app/views/articles/index.html.erb
<div class="container mt-5">
  <h1>Moshi Articles</h1>
  <%= render 'articles/articles' %>
  <div class="digg_pagination">
    <%= will_paginate @articles, :page_links => false %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container mt-5">
  <%= link_to "Go back", articles_path, class: "btn-small btn-underline" %>
  <h1 class="mt-3">Create a new article</h1>
  <%= render 'articles/form' %>

</div>

app/views/articles/show.html.erb
<div class="article-show">
  <div class="article-banner" style="background-color: <%= @colors.sample %>">
    <div class="container text-center">
      <h1 class="title"><%= @article.title %></h1>
      <p>--<%= link_to @article.user.username, user_path(@article.user.id) if @article.user %></p>
    </div>

  </div>
  <div class="small-container mt-5 bg-white">
    <p>
      <i class="fa fa-solid fa fa-arrow-left"></i>
      <%= link_to "Go back to Articles", articles_path, class: "btn-small" %>
    </p>

    <% if policy(@article).update? %>
      <%= link_to "Edit article", edit_article_path(@article), class: "btn-small" %> |
      <%= link_to "Delete article", article_path(@article),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
        class: "btn-small text-danger" %>
    <% end %>
    <hr>
    <p><%= @article.description %></p>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer mt-auto py-2">
  <p class="text-center">Coded by María C.</p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <p class="notice">
    <%= message %>
  </p>
<% end %>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container container-fluid">
    <%= link_to "MOSHI BLOG", root_path, :class => "nav-li logo" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active"><%= link_to "Articles", articles_path, :class => "nav-li btn-small mb-0"%></li>
          <li><%= link_to "Writers", users_path, :class => "nav-li btn-small mb-0" %></li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Create a new article", new_article_path, class: "nav-li btn-small mb-0"%>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag(current_user.photo.key, { class: "avatar dropdown-toggle", id: "navbarDropdown", "data-bs-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false" }) %>
              <% else %>
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn-sharp" %>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/8013b0f68f.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/nav' %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-5">

  <h1>About page</h1>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-color: <%= @colors.sample %>">
  <div class="container banner-content">
    <h1>MOSHI BLOG</h1>
    <p>Where interesting minds come together</p>
    <% if user_signed_in? %>
      <%= link_to "Write something amazing", new_article_path, class: "btn-sharp" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "btn-sharp" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="form signup mt-3">
  <%= simple_form_for @user do |f| %>
    <%= f.input :username, label: "Username" %>
    <%= f.input :email, label: "Enter your email address" %>
    <%= f.input :password_digest, label: "Password" %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, label: (@user.new_record? ? "Signup" : "Update account"), class: "btn-sharp" %>
  <% end %>

  <%= link_to "Delete my account", user_path(@user), data: { turbo_method: :delete,
  turbo_confirm: "You will lose your account and all your articles, are you sure you want to continue?" } %>
</div>

app/views/users/_user_profile.html.erb
<div class="row container mb-5 py-5 border-bottom d-flex align-items-center">
  <%# column 1 %>
  <div class="col-12 col-md-7 p-3">
    <div class="col-12 d-flex align-items-center">
        <div class="user-img-container"
      style="background-image: url(<%= @user.photo.attached? ? cl_image_path(@user.photo.key) :
      'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80'%>)">
      </div>
      <div class="user-data">
        <h3>Hi, I am <%= @user.username %></h3>
        <% if @user.articles.any? %>
          <p class="tag">Posts: <%= @user.articles.count %></p>
        <% else %>
          <p>No posts</p>
        <% end %>
        <% if policy(@user).update? %>
          <%= link_to "Edit profile", edit_user_path(@user), class: "btn-small block" %>
        <% end %>
      </div>
    </div>
  </div>

  <%# column 2%>
  <div class="col-12 col-md-5">
    <div class="col-12 border-left">
      <div class="p-3">
        <p class="fw-bold">A little bit about me</p>
        <p>I like oceans, writting and coding on my free time! 🌊👩🏼‍💻🖋</p>
      </div>
      <ul class="social-buttons">
        <li><i class="fa fa-brands fa fa-instagram"></i></li>
        <li><i class="fa fa-brands fa fa-twitter"></i></li>
        <li><i class="fa fa-brands fa fa-linkedin"></i></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-5">

  <h1>Edit your account information</h1>
  <%= render 'users/form' %>

</div>

app/views/users/index.html.erb
<div class="container mt-5">

  <h1>Our amazing writers</h1>

  <div class="row mt-3">
    <% @users.each do |user| %>
      <div class="col-12 col-md-4 ">
        <div class="col-12 user-card d-flex flex-column align-items-center">
          <div class="small-img mb-2" style="background-image: url(<%= user.photo.attached? ? cl_image_path(user.photo.key) :
          'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80' %>)">
          </div>
          <div>
            <h5><%= link_to user.username, user_path(user)%></h5>
            <% if user.articles.any? %>
              <p><%= user.articles.count %> posts</p>
            <% else %>
              <p>No posts</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container mt-5">

  <h1>Sign up form</h1>
  <%= render 'users/form' %>

</div>

app/views/users/show.html.erb
<div class="container my-5">

  <%= render 'users/user_profile' %>

  <div class="col-md-12 my-3 col-lg-5 p-0">
  <h3>Articles by <%= @user.username %></h3>
    <% if @user.articles.any? %>
      <% @user.articles.each do |article| %>
        <div class="article-simple">
          <h5><%= link_to article.title, article_path(article) %></h5>
          <p class="text-secondary"><small>Published on <%= (article.created_at).strftime('%m/%d/%Y') %></small></p>
        </div>
      <% end %>
    <% else %>
      <p>Sorry, the user <%= @user.username %> still has no posts!</p>
    <% end %>
  </div>

</div>